version: '3.8'
services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8061:8061"
    networks:
      - content-network

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    networks:
      - content-network

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    networks:
      - content-network

  comment-service:
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    container_name: comment-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
    networks:
      - content-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8062:8062"
    networks:
      - content-network

networks:
  content-network:
    driver: bridge
